### PR TITLE
change CardContainer and change card to group

### PR DESCRIPTION
**Pull request by vmjcv**
I made the following changes
1. use group to control button not get_children(), So that others don’t rely on the same structure
2. use onready var manipulation_buttons = $Control/ManipulationButtons, Getting the node in advance can not get_node every time it is used, and can make the code shorter
3. delete _on_button_mouse_entered，This can cause problems when the mouse moves
4. Apply animation to buttons instead of ManipulationButtons
5. use custom seed. This allows the same random number to lead to the same game
6. separate _ready()
7. modify get_all_cards and shuffle_cards

### CODE REVIEW

**Comment by db0** [comment]
Thanks for participating. Could you please merge the latest changes from my main, put your changes into a branch, and then open a pull request via that branch? This allows me to review the changes easier. 

Some issues I see:

- **Most Important:** Please make sure all existing GUT tests work after you're done. First time I tried, game crashed on focus, and I see you just sent a fix for that. I would like the code to be thoroughly tested before being merged, especially when there's so many changes together. At the least the existing tests should return no problems, which should catch any regression bugs. At the moment GUT tests don't run at all and I got a warning that there's something missing when I first opened your project, so something broke.
-  You changed the card shuffling code, but I don't see you re-arranging the cards in the node anymore. This is necessary because the game now displays the card stack and if you don't rearrange the cards it's going to look messed up.
- Please add comments to new functions to explain what they do, in a similar function to others. 

In the future, I would appreciate if each component you change is its own branch. Then I can review them individually instead of having to review hundreds of line of multiple changes in functionality. 

For example, this pull request could have been 4 distinct branches

- mapping nodes to onready variables for readability
- Refactoring _ready()
- Changing random seed and card shuffling
- Manipulation buttons modulate themselves

Again, thanks for the effort. Once the GUT tests are running I can review again and see if any regression bugs were introduced.

**Comment by db0** [comment]
BTW,I just wrote a [contribution guide](https://github.com/db0/godot-card-gaming/blob/main/contributing.md) as well.

**Comment by vmjcv** [comment]
Thank you very much for your reply, I will try to cut it into different functional branches to complete the function (the first time I did a merge submission, I was a bit unskilled)

**Comment by vmjcv** [comment]
I will close this and create a few new merge codes

**Pull request closed without merging**
