### PR TITLE
use custom seed

### PR DESCRIPTION
**Pull request by vmjcv**
1. use custom seed. This allows the same random number to lead to the same game

### CODE REVIEW

**Comment by db0** [comment]
If you want the whole game to be the same, the random seed should be put in cfc. Otherwise each CardContainer has their own random seed, no?

**Comment by vmjcv** [comment]
Yes, I understand what you said, I try the cfc module (I didn’t fully understand the meaning of the cfc module, so I put it in CardContainer)

**Comment by vmjcv** [comment]
I think shuffle_array should not be in CardContainer, but in another module. Can you tell me where it should be placed?

**Comment by db0** [comment]
Ye as we discussed, let's move with a Utils.gd file. Put the array_shuffle() there and see if you can also put the seed there as well. When you push new commits in the same branch, they will appear here for me to review. Also merge the changes from the main in this branch first, as I see there's conflicts now.

**Pull request merged**
